export enum KeyTableCommandTypeStart {
  Alle_Ausgänge = "Alle Ausgänge",
  Ändere_Regler = "Ändere Regler",
  Ausg = "Ausg",
  LED = "LED",
  Leerkommando = "Leerkommando",
  Relais_Timer = "Relais-Timer",
  Relais = "Relais",
  Rollladen_umsteuern = "Rollladen umsteuern",
  Sende_Tasten = "Sende Tasten",
  Sperre_Tasten = "Sperre Tasten",
  Statusbefehl_des_Schwellenwertes_wiederholen = "Statusbefehl des Schwellenwertes wiederholen",
  Subtrahiere = "Subtrahiere",
  Szene = "Szene",
  Tabelle_A = "Tabelle A",
  Tabelle_B = "Tabelle B",
  Tabelle_C = "Tabelle C",
  Tabelle_D = "Tabelle D",
  Unprogrammiert = "Unprogrammiert",
  Wiederhole_Binärsensor = "Wiederhole Binärsensor",
  Wiederhole_Relais = "Wiederhole Relais",
}
